---
uninstall_wait_timeout: |
  {{
    lookup("env", "UNINSTALL_WAIT_TIMEOUT")
      | default("3600", true)
      | int
  }}

patterns_operator_namespace: >-
  {{
    lookup("env", "PATTERNS_OPERATOR_NAMESPACE")
      | default("patterns-operator", true)
  }}
