- name: Assert the required variables are defined
  ansible.builtin.assert:
    that:
      - VP_SPOKECONFIG is defined
      - VP_SPOKECONFIG | length > 0
      - VP_HUBCONFIG is defined
      - VP_HUBCONFIG | length > 0

- name: Output configs
  ansible.builtin.debug:
    msg: "VP_HUBCONFIG: {{ VP_HUBCONFIG }} - VP_SPOKECONFIG: {{ VP_SPOKECONFIG }}"

- name: Fetch regional cluster info
  ansible.builtin.include_tasks:
    file: region-fetch-api.yml
    apply:
      environment:
        KUBECONFIG: "{{ VP_SPOKECONFIG }}"
  when:
    - region_cluster_name is not defined

- name: Add the regional cluster to the ACM hub
  ansible.builtin.include_tasks:
    file: hub-acm-add-regional-cluster.yml
    apply:
      environment:
        KUBECONFIG: "{{ VP_HUBCONFIG }}"
