---
# Once V1 support is dropped we can remove the whole secret_template support
- name: Set secret_template fact
  no_log: "{{ hide_sensitive_output | default(true) }}"
  ansible.builtin.set_fact:
    secret_template: "{{ pattern_dir }}/values-secret.yaml.template"

- name: Resolve VALUES_SECRET for primary secrets search
  ansible.builtin.set_fact:
    custom_env_values_secret: "{{ lookup('ansible.builtin.env', 'VALUES_SECRET') | default('', true) }}"

- name: Check if VALUES_SECRET file exists
  ansible.builtin.stat:
    path: "{{ custom_env_values_secret }}"
  register: custom_file_values_secret
  when: custom_env_values_secret | default('') | length > 0

- name: Set values-secret yaml file to {{ custom_file_values_secret.stat.path | default('unset') }}
  ansible.builtin.set_fact:
    found_file: "{{ custom_file_values_secret.stat.path }}"
  when:
    - custom_file_values_secret.stat is defined
    - custom_file_values_secret.stat.exists
    - custom_env_values_secret | default('') | length > 0

# FIXME(bandini): Eventually around end of 2023(?) we should drop
# ~/values-secret-{{ pattern_name }}.yaml and ~/values-secret.yaml
- name: Find first existing values-secret yaml file
  ansible.builtin.set_fact:
    found_file: "{{ lookup('ansible.builtin.first_found', findme) }}"
  vars:
    findme:
      - "~/.config/hybrid-cloud-patterns/values-secret-{{ pattern_name }}.yaml"
      - "~/.config/validated-patterns/values-secret-{{ pattern_name }}.yaml"
      - "~/values-secret-{{ pattern_name }}.yaml"
      - "~/values-secret.yaml"
      - "{{ pattern_dir }}/values-secret.yaml.template"
  when: custom_env_values_secret | default('') | length == 0

- name: Read secrets from discovered file
  ansible.builtin.include_tasks: read_secret_from_path.yml
