---
- name: Announce yq check
  ansible.builtin.shell: |
    printf "==> Checking yq availability... " > /dev/tty

- name: Probe yq version
  ansible.builtin.command: yq --version
  register: _yq_probe
  failed_when: false

- name: Report yq version to TTY (if installed)
  ansible.builtin.shell: |
    printf "OK (%s)\n" "{{ _yq_probe.stdout }}" > /dev/tty
  when: _yq_probe.rc == 0

- name: Print yq missing/error message and exit (if not installed)
  ansible.builtin.shell: |
    printf "ERROR\n" > /dev/tty
    printf "    yq is not installed or not on PATH.\n" > /dev/tty
    printf "    Hint: Install yq and ensure 'yq' is resolvable.\n" > /dev/tty
    exit 1
  when: _yq_probe.rc != 0
