---
- name: Wait for secrets namespace to exist
  when: (secrets_install_phase | default(secrets_phase | default('late'))) != 'early'
  no_log: '{{ hide_sensitive_output | default(true) }}'
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ item['metadata']['namespace'] }}"
  register: secrets_ns_rc
  until: secrets_ns_rc.resources | length > 0
  retries: 20
  delay: 45

- name: Inject k8s secret
  no_log: '{{ hide_sensitive_output | default(True) }}'
  kubernetes.core.k8s:
    definition: '{{ item }}'
