---
- name: Wait for namespace {{ _k8s_secret_object.metadata.namespace }} (secret {{ _k8s_secret_object.metadata.name }})
  when: (secrets_install_phase | default(secrets_phase | default('late'))) != 'early'
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ _k8s_secret_object.metadata.namespace }}"
  register: secrets_ns_rc
  until: secrets_ns_rc.resources | length > 0
  retries: 20
  delay: 45
  changed_when: false

- name: Inject Kubernetes secret {{ _k8s_secret_object.metadata.namespace }}/{{ _k8s_secret_object.metadata.name }}
  no_log: '{{ hide_sensitive_output | default(True) }}'
  kubernetes.core.k8s:
    definition: '{{ _k8s_secret_object }}'
