---
- name: Run interop test
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: pattern_settings # set general pattern vars

  tasks:

  - name: Resolve and set some pattern related vars (same as install_settings)
    ansible.builtin.include_role:
      name: install_settings
      tasks_from: resolve_overrides

  - name: Run pytest with clustergroup {{ target_variant }}
    ansible.builtin.command:
      cmd: pytest -lv test_{{ target_variant }}.py --junit-xml .results/test_{{ target_variant }}.xml
      chdir: "{{ pattern_dir }}/tests/ci/"
    environment:
      WORKSPACE: "{{ pattern_dir }}/tests/ci/"
    changed_when: false
    register: pytest_out

  - name: Log pytest output
    ansible.builtin.debug:
      msg: "{{ pytest_out.stdout }}"
