---
- name: Run super-linter locally
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    disable_linter_flags: "{{ lookup('env', 'DISABLE_LINTERS') | default('', true) }}"
  tasks:
    - name: Load defaults
      ansible.builtin.include_role:
        name: pattern_defaults

    - name: Remove mypy cache
      ansible.builtin.file:
        path: "{{ pattern_dir }}/.mypy_cache"
        state: absent

    - name: Run super-linter container
      ansible.builtin.shell:
        cmd: >-
          podman run -e RUN_LOCAL=true -e USE_FIND_ALGORITHM=true
          -e VALIDATE_ANSIBLE=false
          -e VALIDATE_BASH=false
          -e VALIDATE_CHECKOV=false
          -e VALIDATE_DOCKERFILE_HADOLINT=false
          -e VALIDATE_JSCPD=false
          -e VALIDATE_JSON_PRETTIER=false
          -e VALIDATE_MARKDOWN_PRETTIER=false
          -e VALIDATE_KUBERNETES_KUBECONFORM=false
          -e VALIDATE_PYTHON_PYLINT=false
          -e VALIDATE_SHELL_SHFMT=false
          -e VALIDATE_TEKTON=false
          -e VALIDATE_YAML=false
          -e VALIDATE_YAML_PRETTIER=false
          {{ disable_linter_flags }}
          -v {{ pattern_dir }}:/tmp/lint:rw,z
          -w /tmp/lint
          ghcr.io/super-linter/super-linter:slim-v8 > /dev/tty
