---
- name: Validates the pattern's git remote is reachable
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: pattern_settings # set general pattern vars
    - role: install_settings # set pattern-install specific vars
    - role: validate_origin
