---
- name: Validates cluster connectivity, storage class, and OCP version compatibility
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: pattern_settings # set general pattern vars
    - role: install_settings # set pattern-install specific vars
    - role: validate_cluster
    - role: validate_ocp_version
